TRANSPOSE OF THE MATRICES

In [5]:
import numpy as np 
matrixA = np.matrix('3,-5;-2,7')
matrixB = np.matrix('2, -3, -4;-5, 6, 7;-8, 9, 1')
tmatA = np.transpose(matrixA)
tmatB = np.transpose(matrixB)
print(matrix1)
print(tmatA)
print(tmatB)

[[ 3 -5]
 [-2  7]]
[[ 3 -2]
 [-5  7]]
[[ 2 -5 -8]
 [-3  6  9]
 [-4  7  1]]


ELEMENT-WISE PRODUCT OF A AND B MATRICES - A*B

In [9]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('2, -3, -4;-5, -6, 7;-8, 9, 1')
element_wise_product = np.multiply(matrixA, matrixB)
print(element_wise_product)

[[  6  -6   4]
 [ 10 -42  28]
 [ -8  54   8]]


MATRIX PRODUCT OF A AND B MATRICES - AB

In [8]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('2, -3, -4;-5, -6, 7;-8, 9, 1')
product_of_matrices = np.matmul(matrixA, matrixB)
print(product_of_matrices)

[[  4 -30   1]
 [-71   0  61]
 [-92  33  46]]


ELEMENT-WISE PRODUCT OF B AND A MATRICES - B*A

In [10]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('2, -3, -4;-5, -6, 7;-8, 9, 1')
element_wise_product = np.multiply(matrixB, matrixA)
print(element_wise_product)

[[  6  -6   4]
 [ 10 -42  28]
 [ -8  54   8]]


MATRIX PRODUCT OF B AND A MATRICES - BA

In [11]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('2, -3, -4;-5, -6, 7;-8, 9, 1')
product_of_matrices = np.matmul(matrixB, matrixA)
print(product_of_matrices)

[[  8 -41 -46]
 [  4 -10  37]
 [-41  53  52]]


INVERTION OF MATRICES

In [14]:
import numpy as np 
matrixA = np.matrix('3, 2;-2, 7')
matrixB = np.matrix('4, 0;0, 5')
inversion_of_matrixA = np.linalg.inv(matrixA)
inversion_of_matrixB = np.linalg.inv(matrixB)
print(inversion_of_matrixA)
print(inversion_of_matrixB)

[[ 0.28 -0.08]
 [ 0.08  0.12]]
[[0.25 0.  ]
 [0.   0.2 ]]


TRANSPOSE OF MATRICES

In [45]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('-1, 2, 3;5, -4, 9;-7, 8, 6')
matrixC = np.matrix('-5, 4, 9;6, 1, 3;7, 2, -8')
TranA = np.transpose(matrixA)
TranB = np.transpose(matrixB)

#Transpose of At == A
if (TranA == matrixA).all():
    print('True')
else:
    print('False')

#Transpose of (A+B) = At + Bt
if (np.transpose(matrixA + matrixB) == TranA + TranB).all():
    print('True')
else:
    print('False')


False
True


MATRICES RELATIONS

In [44]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('-1, 2, 3;5, -4, 9;-7, 8, 6')
matrixC = np.matrix('-5, 4, 9;6, 1, 3;7, 2, -8')
#A+B=B+A
if (matrixA + matrixB == matrixB+matrixA).all():
    print('True')
else:
    print('False')
#A+(B+C)=(A+B)+C
if(matrixA + (matrixB + matrixC) == (matrixA + matrixB) + matrixC).all():
    print('True')
else:
    print('False')

    

True
True


MATRIX PRODUCT

In [53]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('-1, 2, 3;5, -4, 9;-7, 8, 6')
matrixC = np.matrix('-5, 4, 9;6, 1, 3;7, 2, -8')
prAB = np.matmul(matrixA, matrixB)
prBA = np.matmul(matrixB, matrixA)
prBC = np.matmul(matrixB, matrixC)
prAC = np.matmul(matrixA, matrixC)
TranA = np.transpose(matrixA)
TranB = np.transpose(matrixB)

#AB != BA
if (prAB!=prBA).all():
   print('True')
else:
    print('False')

#A(BC) = (AB)C
if (np.matmul(matrixA,prBC) == np.matmul(prAB, matrixC)).all():
    print('True')
else:
    print('False')

#A(B+C) = AB + AC
if(np.matmul(matrixA,(matrixB+matrixC)) == prAB + prAC).all():
    print('True')
else:
    print('False')

#(AB)t = BtAt
if(np.transpose(prAB) == np.matmul(TranB,TranA)).all():
    print('True')
else:
    print('False')


True
True
True
True


INVERSION

In [77]:
import numpy as np 
matrixA = np.matrix('3, 2, -1;-2, 7, 4;1, 6, 8')
matrixB = np.matrix('-1, 2, 3;5, -4, 9;-7, 8, 6')

prAB = np.matmul(matrixA, matrixB)
invA = np.linalg.inv(matrixA)
invB = np.linalg.inv(matrixB)
invAB = np.linalg.inv(prAB)
TranA = np.transpose(matrixA)
TranB = np.transpose(matrixB)
a=2
b=3

# (AB)^-1 = B^-1A^-1
if (invAB == np.matmul(invB, invA)).all():
    print('True')
else:
    print('False')

#(At)^-1 = (A^-1)t
if (np.linalg.inv(TranA) == np.transpose(invA)).all():
    print('True')
else:
    print('False')

#(a+b)A = aA +bA
if((a+b)*matrixA == a*matrixA + b*matrixA).all():
    print('True')
else:
    print('False')

#a(A+B) = aA + aB
if(a*(matrixA + matrixB) == a*matrixA + a*matrixB).all():
    print('True')
else:
    print('False')

#(aA)^-1 = a^-1A^-1
if(np.linalg.inv((a*matrixA)) == invA/a).all():
    print('True')
else:
    print('False')


False
False
True
True
True
